const seedActivities = [
  {
    name: "Regarder un film comique",
    location: ["interieur"],
    min_players: 1,
    max_players: 8,
    category: "calme",
    energy: "calme",
    type: ["détente"],
    duration: "long",
    material: "oui",
    noise: "silencieux",
    mood : "te vider la tête",
    objectif : "passer le temps",
    result: "non",
    meteo: "",
    social: "coopératif",
    interrupt: "non",
    moment: "",
    school:"oui",
  },
  {
    name: "Jouer au Uno",
    location: ["interieur"],
    min_players: 2,
    max_players: 6,
    category: "jeux de société",
    energy: "moyen",
    type: ["jeu"],
    duration: "court",
    material: "oui",
    noise: "moyen",
    mood : "te sentir fier",
    objectif : "passer le temps",
    result: "non",
    meteo: "",
    social: "compétitif",
    interrupt: "non",
    moment: "",
    school:"oui",
  },
  {
    name: "Jouer au Scrabble",
    location: ["interieur"],
    min_players: 2,
    max_players: 4,
    category: "jeux de société",
    energy: "calme",
    type: ["jeu", "éducatif"],
    duration: "long",
    material: "oui",
    noise: "silencieux",
    mood : "te stimuler",
    objectif : "passer le temps",
    result: "non",
    meteo: "",
    social: "compétitif",
    interrupt: "non",
    moment: "",
    school:"oui",
  },
  {
    name: "Faire du velo",
    location: ["exterieur"],
    min_players: 1,
    max_players: 6,
    category: "sport",
    energy: "élevé",
    type: ["sport"],
    duration: "moyen",
    material: "oui",
    noise: "moyen",
    mood : "te stimuler",
    objectif : "te défouler",
    result: "non",
    meteo: "soleil",
    social: "coopératif",
    interrupt: "non",
    moment: "jour",
    school:"non",
  },
  {
    name: "Faire du yoga pour enfants",
    location: ["interieur", "exterieur"],
    min_players: 1,
    max_players: 8,
    category: "sport",
    energy: "calme",
    type: ["sport", "détente"],
    duration: "court",
    material: "non",
    noise: "silencieux",
    mood : "te stimuler",
    objectif : "te défouler",
    result: "non",
    meteo: "",
    social: "coopératif",
    interrupt: "oui",
    moment: "jour",
    school:"non",
  },
  {
    name: "Faire un pique-nique",
    location: ["exterieur"],
    min_players: 2,
    max_players: 10,
    category: "plein air",
    energy: "calme",
    type: ["détente"],
    duration: "moyen",
    material: "oui",
    noise: "moyen",
    mood : "te réconforter",
    objectif : "créer un souvenir",
    result: "non",
    meteo: "soleil",
    social: "coopératif",
    interrupt: "non",
    moment: "jour",
    school:"non",
  },
  {
    name: "Profiter de la cabane",
    location: ["interieur", "exterieur"],
    min_players: 1,
    max_players: 6,
    category: "plein air",
    energy: "moyen",
    type: ["créatif", "jeu"],
    duration: "moyen",
    material: "oui",
    noise: "moyen",
    mood : "te vider la tête",
    objectif : "passer le temps",
    result: "non",
    meteo: "soleil",
    social: "coopératif",
    interrupt: "oui",
    moment: "jour",
    school:"oui",
  },
  {
    name: "Dessiner",
    location: ["interieur"],
    min_players: 1,
    max_players: 6,
    category: "créatif",
    energy: "calme",
    type: ["créatif"],
    duration: "court",
    material: "oui",
    noise: "silencieux",
    mood : "te stimuler",
    objectif : "progresser",
    result: "oui",
    meteo: "",
    social: "compétitif",
    interrupt: "non",
    moment: "",
    school:"oui",
  },
  {
    name: "Construire en Lego",
    location: ["interieur"],
    min_players: 1,
    max_players: 4,
    category: "créatif",
    energy: "calme",
    type: ["créatif", "jeu"],
    duration: "moyen",
    material: "oui",
    noise: "silencieux",
    mood : "te sentir fier",
    objectif : "passer le temps",
    result: "oui",
    meteo: "",
    social: "coopératif",
    interrupt: "non",
    moment: "",
    school:"oui",
  },
  {
    name: "Faire un spectacle",
    location: ["interieur", "exterieur"],
    min_players: 2,
    max_players: 8,
    category: "imaginatif",
    energy: "élevé",
    type: ["créatif", "jeu"],
    duration: "moyen",
    material: "oui",
    noise: "bruyant",
    mood : "te sentir fier",
    objectif : "créer un souvenir",
    result: "non",
    meteo: "",
    social: "coopératif",
    interrupt: "non",
    moment: "jour",
    school:"non",
  },
  {
    name: "Faire un gateau",
    location: ["interieur"],
    min_players: 1,
    max_players: 6,
    category: "cuisine",
    energy: "moyen",
    type: ["créatif", "éducatif"],
    duration: "moyen",
    material: "oui",
    noise: "moyen",
    mood : "te réconforter",
    objectif : "passer le temps",
    result: "oui",
    meteo: "",
    social: "coopératif",
    interrupt: "non",
    moment: "jour",
    school:"non",
  },
  {
    name: "Faire des cookies",
    location: ["interieur"],
    min_players: 1,
    max_players: 6,
    category: "cuisine",
    energy: "moyen",
    type: ["créatif"],
    duration: "moyen",
    material: "oui",
    noise: "moyen",
    mood : "te réconforter",
    objectif : "passer le temps",
    result: "oui",
    meteo: "",
    social: "coopératif",
    interrupt: "non",
    moment: "jour",
    school:"non",
  },
  {
    name: "Faire des puzzles",
    location: ["interieur"],
    min_players: 1,
    max_players: 4,
    category: "éducatif",
    energy: "calme",
    type: ["éducatif", "jeu"],
    duration: "moyen",
    material: "oui",
    noise: "silencieux",
    mood : "te stimuler",
    objectif : "progresser",
    result: "non",
    meteo: "",
    social: "coopératif",
    interrupt: "non",
    moment: "",
    school:"oui",
  },
  {
    name: "Faire une experience scientifique",
    location: ["interieur"],
    min_players: 1,
    max_players: 4,
    category: "éducatif",
    energy: "moyen",
    type: ["éducatif", "créatif"],
    duration: "moyen",
    material: "oui",
    noise: "moyen",
    mood : "te stimuler",
    objectif : "progresser",
    result: "oui",
    meteo: "",
    social: "coopératif",
    interrupt: "non",
    moment: "jour",
    school:"non",
  },
  {
    name: "Jouer a un jeu video en famille",
    location: ["interieur"],
    min_players: 1,
    max_players: 6,
    category: "numérique",
    energy: "moyen",
    type: ["jeu", "détente"],
    duration: "court",
    material: "oui",
    noise: "moyen",
    mood : "te vider la tête",
    objectif : "passer le temps",
    result: "non",
    meteo: "",
    social: "compétitif",
    interrupt: "oui",
    moment: "",
    school:"oui",
  },
  {
    name: "Faire un quiz interactif",
    location: ["interieur"],
    min_players: 1,
    max_players: 8,
    category: "numérique",
    energy: "moyen",
    type: ["jeu", "éducatif"],
    duration: "court",
    material: "oui",
    noise: "moyen",
    mood : "te stimuler",
    objectif : "passer le temps",
    result: "non",
    meteo: "",
    social: "coopératif",
    interrupt: "non",
    moment: "",
    school:"non",
    
  },
  {
    name: "Discuter ensemble",
    location: ["interieur", "exterieur"],
    min_players: 2,
    max_players: 8,
    category: "famille",
    energy: "calme",
    type: ["détente"],
    duration: "court",
    material: "non",
    noise: "silencieux",
    mood : "te stimuler",
    objectif : "créer un souvenir",
    result: "non",
    meteo: "",
    social: "coopératif",
    interrupt: "oui",
    moment: "",
    school:"oui",
  },
  {
    name: "Faire un album photo",
    location: ["interieur"],
    min_players: 1,
    max_players: 4,
    category: "famille",
    energy: "calme",
    type: ["créatif", "détente"],
    duration: "moyen",
    material: "oui",
    noise: "silencieux",
    mood : "te réconforter",
    objectif : "créer un souvenir",
    result: "oui",
    meteo: "",
    social: "coopératif",
    interrupt: "non",
    moment: "",
    school:"non",
  },
  {
    name: "Regarder un dessin anime", 
    location: ["interieur"],
    min_players: 1,
    max_players: 8,
    energy: "calme",
    type: ["détente"],
    duration: "moyen",
    material: true,
    noise: "silencieux",
  },
  {
    name:"Regarder un film d'aventure",
    location: ["interieur"],
    min_players: 1,
    max_players: 8,
    energy: "calme",
    type: ["détente"],
    duration: "long",
    material: true,
    noise: "moyen",
  },
  {
    name:"Regarder un documentaire animalier",
    location: ["interieur"],
    min_players: 1,
    max_players: 8,
    energy: "calme",
    type: ["éducatif", "détente"],
    duration: "moyen",
    material: true,
    noise: "silencieux",
  },
  {
    name:"Faire une soiree cinema avec popcorn", 
    location: ["interieur"],
    min_players: 2,
    max_players: 8,
    energy: "calme",
    type: ["détente"],
    duration: "long",
    material: true,
    noise: "moyen",
  },
  {
    name:"Lire une histoire ensemble", 
    location: ["interieur"],
    min_players: 1,
    max_players: 6,
    energy: "calme",
    type: ["éducatif", "détente"],
    duration: "court",
    material: true,
    noise: "silencieux",
  },
  {
    name:"Lire chacun son livre", 
    location: ["interieur"],
    min_players: 1,
    max_players: 6,
    energy: "calme",
    type: ["éducatif", "détente"],
    duration: "moyen",
    material: true,
    noise: "silencieux",
  },
  {
    name:"Ecouter un podcast pour enfants", 
    location: ["interieur"],
    min_players: 1,
    max_players: 6,
    energy: "calme",
    type: ["éducatif", "détente"],
    duration: "court",
    material: true,
    noise: "silencieux",
  },
  {
    name:"Ecouter de la musique relaxante", 
    location: ["interieur"],
    min_players: 1,
    max_players: 8,
    energy: "calme",
    type: ["détente"],
    duration: "court",
    material: true,
    noise: "silencieux",
  },
  {
    name:"Faire une sieste", 
    location: ["interieur"],
    min_players: 1,
    max_players: 4,
    energy: "calme",
    type: ["détente"],
    duration: "court",
    material: false,
    noise: "silencieux",
  },
  {
    name:"Raconter des souvenirs en famille", 
    location: ["interieur"],
    min_players: 2,
    max_players: 8,
    energy: "calme",
    type: ["détente", "éducatif"],
    duration: "court",
    material: false,
    noise: "silencieux",
  },
  {
    name:"Observer les nuages", 
    location: ["exterieur"],
    min_players: 1,
    max_players: 6,
    energy: "calme",
    type: ["détente", "éducatif"],
    duration: "court",
    material: false,
    noise: "silencieux",
  },
  {
    name:"Observer les etoiles", 
    location: ["exterieur"],
    min_players: 1,
    max_players: 6,
    energy: "calme",
    type: ["détente", "éducatif"],
    duration: "moyen",
    material: false,
    noise: "silencieux",
  },
  {
    name:"Jouer au Monopoly", 
    location: ["interieur"],
    min_players: 2,
    max_players: 6,
    energy: "moyen",
    type: ["jeu"],
    duration: "long",
    material: true,
    noise: "moyen",
  },
  {
    name:"Jouer au Cluedo", 
    location: ["interieur"],
    min_players: 2,
    max_players: 6,
    energy: "moyen",
    type: ["créatif", "jeu"],
    type: ["jeu"],
    duration: "long",
    material: true,
    noise: "moyen",
  },
  {
    name:"Jouer au Dobble", 
    location: ["interieur"],
    min_players: 2,
    max_players: 8,
    energy: "moyen",
    type: ["jeu"],
    duration: "court",
    material: true,
    noise: "moyen",
  },
  {
    name:"Jouer au Puissance 4", 
    location: ["interieur"],
    min_players: 2,
    max_players: 2,
    energy: "calme",
    type: ["jeu"],
    duration: "court",
    material: true,
    noise: "silencieux",
  },
  {
    name:"Jouer aux echecs", 
    location: ["interieur"],
    min_players: 2,
    max_players: 2,
    energy: "calme",
    type: ["jeu", "éducatif"],
    duration: "long",
    material: true,
    noise: "silencieux",
  },
  {
    name:"Jouer aux dames", 
    location: ["interieur"],
    min_players: 2,
    max_players: 2,
    energy: "calme",
    type: ["jeu"],
    duration: "moyen",
    material: true,
    noise: "silencieux",
  },
  {
    name:"Jouer au Trivial Pursuit junior", 
    location: ["interieur"],
    min_players: 2,
    max_players: 6,
    energy: "moyen",
    type: ["jeu", "éducatif"],
    duration: "moyen",
    material: true,
    noise: "moyen",
  },
  {
    name:"Jouer a un jeu de cartes invente", 
    location: ["interieur"],
    min_players: 2,
    max_players: 8,
    energy: "moyen",
    type: ["jeu", "créatif"],
    duration: "court",
    material: true,
    noise: "moyen",
  },
  {
    name:"Faire un tournoi de jeux de societe", 
    location: ["interieur"],
    min_players: 3,
    max_players: 8,
    energy: "moyen",
    type: ["jeu"],
    duration: "long",
    material: true,
    noise: "moyen",
  },
  {
    name:"Jouer au jeu de l'oie", 
    location: ["interieur"],
    min_players: 2,
    max_players: 6,
    energy: "calme",
    type: ["jeu"],
    duration: "court",
    material: true,
    noise: "silencieux",
  },
  {
    name:"Jouer au Jungle Speed", 
    location: ["interieur"],
    min_players: 2,
    max_players: 8,
    energy: "élevé",
    type: ["jeu"],
    duration: "court",
    material: true,
    noise: "bruyant",
  },
  {
    name:"Jouer au ballon dehors", 
    location: ["exterieur"],
    min_players: 2,
    max_players: 10,
    energy: "élevé",
    type: ["sport", "jeu"],
    duration: "court",
    material: true,
    noise: "bruyant",
  },
  {
    name:"Faire une course a pied en famille", 
    location: ["exterieur"],
    min_players: 1,
    max_players: 8,
    energy: "élevé",
    type: ["sport"],
    duration: "moyen",
    material: false,
    noise: "moyen",
  },
  {
    name:"Faire du velo", 
    location: ["exterieur"],
    min_players: 1,
    max_players: 6,
    energy: "élevé",
    type: ["sport"],
    duration: "moyen",
    material: true,
    noise: "moyen",
  },
  {
    name:"Faire une balade en trottinette", 
    location: ["exterieur"],
    min_players: 1,
    max_players: 6,
    energy: "moyen",
    type: ["sport"],
    duration: "moyen",
    material: true,
    noise: "moyen",
  },
  {
    name:"Jouer a cache-cache", 
    location: ["interieur", "exterieur"],
    min_players: 2,
    max_players: 10,
    energy: "élevé",
    type: ["jeu", "sport"],
    duration: "court",
    material: false,
    noise: "bruyant",
  },
  {
    name:"Jouer a chat", 
    location: ["exterieur"],
    min_players: 2,
    max_players: 10,
    energy: "élevé",
    type: ["jeu", "sport"],
    duration: "court",
    material: false,
    noise: "bruyant",
  },
  {
    name:"Faire une chasse au tresor", 
    location: ["interieur", "exterieur"],
    min_players: 2,
    max_players: 8,
    energy: "élevé",
    type: ["jeu", "éducatif"],
    duration: "moyen",
    material: true,
    noise: "moyen",
  },
  {
    name:"Faire du football", 
    location: ["exterieur"],
    min_players: 4,
    max_players: 12,
    energy: "élevé",
    type: ["sport"],
    duration: "moyen",
    material: true,
    noise: "bruyant",
  },
  {
    name:"Faire du basket", 
    location: ["exterieur"],
    min_players: 2,
    max_players: 10,
    energy: "élevé",
    type: ["sport"],
    duration: "moyen",
    material: true,
    noise: "bruyant",
  },
  {
    name:"Faire un parcours d'obstacles", 
    location: ["interieur", "exterieur"],
    min_players: 1,
    max_players: 8,
    energy: "élevé",
    type: ["sport", "jeu"],
    duration: "court",
    material: true,
    noise: "bruyant",
  },
  {
    name:"Danser ensemble", 
    location: ["interieur", "exterieur"],
    min_players: 1,
    max_players: 8,
    energy: "élevé",
    type: ["sport", "détente"],
    duration: "court",
    material: true,
    noise: "bruyant",
  },
  {
    name:"Faire des etirements", 
    location: ["interieur", "exterieur"],
    min_players: 1,
    max_players: 8,
    energy: "calme",
    type: ["sport", "détente"],
    duration: "court",
    material: false,
    noise: "silencieux",
  },
  {
    name:"Faire une bataille de coussins", 
    location: ["interieur"],
    min_players: 2,
    max_players: 6,
    energy: "élevé",
    type: ["jeu", "sport"],
    duration: "court",
    material: true,
    noise: "bruyant",
  },
  {
    name:"Faire un relais sportif", 
    location: ["exterieur"],
    min_players: 3,
    max_players: 10,
    energy: "élevé",
    type: ["sport", "jeu"],
    duration: "court",
    material: false,
    noise: "bruyant",
  },
  {
    name:"Aller au parc", 
    location: ["exterieur"],
    min_players: 1,
    max_players: 8,
    energy: "moyen",
    type: ["détente", "sport"],
    duration: "moyen",
    material: false,
    noise: "moyen",
  },
  {
    name:"Se promener en foret", 
    location: ["exterieur"],
    min_players: 1,
    max_players: 8,
    energy: "moyen",
    type: ["détente", "éducatif"],
    duration: "moyen",
    material: false,
    noise: "silencieux",
  },
  {
    name:"Aller a la plage", 
    location: ["exterieur"],
    min_players: 1,
    max_players: 8,
    energy: "moyen",
    type: ["détente", "sport"],
    duration: "long",
    material: true,
    noise: "moyen",
  },
  {
    name:"Construire une cabane", 
    location: ["interieur", "exterieur"],
    min_players: 1,
    max_players: 6,
    energy: "moyen",
    type: ["créatif", "jeu"],
    duration: "moyen",
    material: true,
    noise: "moyen",
  },
  {
    name:"Jouer dans le jardin", 
    location: ["exterieur"],
    min_players: 1,
    max_players: 8,
    energy: "moyen",
    type: ["jeu", "sport"],
    duration: "moyen",
    material: false,
    noise: "moyen",
  },
  {
    name:"Faire du cerf-volant", 
    location: ["exterieur"],
    min_players: 1,
    max_players: 6,
    energy: "moyen",
    type: ["sport", "détente"],
    duration: "moyen",
    material: true,
    noise: "moyen",
  },
  {
    name:"Ramasser des feuilles ou des fleurs", 
    location: ["exterieur"],
    min_players: 1,
    max_players: 6,
    energy: "calme",
    type: ["éducatif", "détente"],
    duration: "court",
    material: false,
    noise: "silencieux",
  },
  {
    name:"Observer les insectes", 
    location: ["exterieur"],
    min_players: 1,
    max_players: 6,
    energy: "calme",
    type: ["éducatif"],
    duration: "court",
    material: false,
    noise: "silencieux",
  },
  {
    name:"Faire une balade nature", 
    location: ["exterieur"],
    min_players: 1,
    max_players: 8,
    energy: "moyen",
    type: ["détente", "éducatif"],
    duration: "moyen",
    material: false,
    noise: "silencieux",
  },
  {
    name:"Nourrir les canards", 
    location: ["exterieur"],
    min_players: 1,
    max_players: 6,
    energy: "calme",
    type: ["détente", "éducatif"],
    duration: "court",
    material: true,
    noise: "silencieux",
  },
  {
    name:"Faire une chasse aux tresors naturelle", 
    location: ["exterieur"],
    min_players: 2,
    max_players: 8,
    energy: "moyen",
    type: ["jeu", "éducatif"],
    duration: "moyen",
    material: false,
    noise: "moyen",
  },
  {
    name:"Faire un barbecue", 
    location: ["exterieur"],
    min_players: 2,
    max_players: 10,
    energy: "moyen",
    type: ["détente", "créatif"],
    duration: "long",
    material: true,
    noise: "moyen",
  },
  {
    name:"Jardiner", 
    location: ["exterieur"],
    min_players: 1,
    max_players: 6,
    energy: "moyen",
    type: ["éducatif", "créatif"],
    duration: "moyen",
    material: true,
    noise: "silencieux",
  },
  {
    name:"Planter des graines", 
    location: ["exterieur"],
    min_players: 1,
    max_players: 6,
    energy: "calme",
    type: ["éducatif", "créatif"],
    duration: "court",
    material: true,
    noise: "silencieux",
  },
  {
    name:"Peindre", 
    location: ["interieur", "exterieur"],
    min_players: 1,
    max_players: 6,
    energy: "calme",
    type: ["créatif"],
    duration: "moyen",
    material: true,
    noise: "silencieux",
  },
  {
    name:"Colorier", 
    location: ["interieur"],
    min_players: 1,
    max_players: 6,
    energy: "calme",
    type: ["créatif"],
    duration: "court",
    material: true,
    noise: "silencieux",
  },
  {
    name:"Faire du collage", 
    location: ["interieur"],
    min_players: 1,
    max_players: 6,
    energy: "calme",
    type: ["créatif"],
    duration: "court",
    material: true,
    noise: "silencieux",
  },
  {
    name: "Atelier dessin",
  },
  {
    name:"Creer une bande dessinee", 
    location: ["interieur"],
    min_players: 1,
    max_players: 4,
    energy: "calme",
    type: ["créatif", "éducatif"],
    duration: "moyen",
    material: true,
    noise: "silencieux",
  },
  {
    name:"Fabriquer un objet en papier", 
    location: ["interieur"],
    min_players: 1,
    max_players: 6,
    energy: "calme",
    type: ["créatif"],
    duration: "court",
    material: true,
    noise: "silencieux",
  },
  {
    name:"Faire de la pate a modeler", 
    location: ["interieur"],
    min_players: 1,
    max_players: 5,
    energy: "calme",
    type: ["créatif"],
    duration: "court",
    material: true,
    noise: "silencieux",
  },
  {
    name:"Creer une maquette", 
    location: ["interieur"],
    min_players: 1,
    max_players: 4,
    energy: "calme",
    type: ["créatif", "éducatif"],
    duration: "long",
    material: true,
    noise: "silencieux",
  },
  {
    name:"Inventer une histoire", 
    location: ["interieur"],
    min_players: 1,
    max_players: 6,
    energy: "calme",
    type: ["créatif", "éducatif"],
    duration: "court",
    material: false,
    noise: "silencieux",
  },
  {
    name:"Faire du bricolage", 
    location: ["interieur", "exterieur"],
    min_players: 1,
    max_players: 6,
    energy: "moyen",
    type: ["créatif"],
    duration: "moyen",
    material: true,
    noise: "moyen",
  },
  {
    name:"Fabriquer un cadeau", 
    location: ["interieur"],
    min_players: 1,
    max_players: 4,
    energy: "calme",
    type: ["créatif"],
    duration: "moyen",
    material: true,
    noise: "silencieux",
  },
  {
    name:"Creer un deguisement", 
    location: ["interieur"],
    min_players: 1,
    max_players: 4,
    energy: "moyen",
    type: ["créatif", "jeu"],
    duration: "moyen",
    material: true,
    noise: "moyen",
  },
  {
    name:"Faire un atelier DIY", 
    location: ["interieur"],
    min_players: 1,
    max_players: 6,
    energy: "calme",
    type: ["créatif"],
    duration: "moyen",
    material: true,
    noise: "silencieux",
  },
  {
    name:"Peindre des cailloux", 
    location: ["interieur", "exterieur"],
    min_players: 1,
    max_players: 6,
    energy: "calme",
    type: ["créatif"],
    duration: "court",
    material: true,
    noise: "silencieux",
  },
  {
    name:"Faire une soiree pyjama", 
    location: ["interieur"],
    min_players: 2,
    max_players: 6,
    energy: "moyen",
    type: ["détente", "jeu"],
    duration: "long",
    material: true,
    noise: "moyen",
  },
  {
    name:"Jouer a se deguiser", 
    location: ["interieur"],
    min_players: 1,
    max_players: 6,
    energy: "moyen",
    type: ["jeu", "créatif"],
    duration: "court",
    material: true,
    noise: "moyen",
  },
  {
    name:"Jouer une piece de theatre", 
    location: ["interieur", "exterieur"],
    min_players: 2,
    max_players: 8,
    energy: "moyen",
    type: ["créatif", "jeu"],
    duration: "moyen",
    material: true,
    noise: "moyen",
  },
  {
    name:"Inventer un jeu", 
    location: ["interieur", "exterieur"],
    min_players: 1,
    max_players: 6,
    energy: "moyen",
    type: ["éducatif", "jeu"],
    type: ["créatif", "jeu"],
    duration: "moyen",
    material: false,
    noise: "moyen",
  },
  {
    name:"Faire un karaoke", 
    location: ["interieur"],
    min_players: 1,
    max_players: 8,
    energy: "élevé",
    type: ["jeu", "détente"],
    duration: "court",
    material: true,
    noise: "bruyant",
  },
  {
    name:"Raconter des blagues", 
    location: ["interieur", "exterieur"],
    min_players: 2,
    max_players: 8,
    energy: "moyen",
    type: ["jeu", "détente"],
    duration: "court",
    material: false,
    noise: "moyen",
  },
  {
    name: "Parcours moteur",
  },
  {
    name:"Jouer aux devinettes", 
    location: ["interieur", "exterieur"],
    min_players: 2,
    max_players: 8,
    energy: "calme",
    type: ["jeu", "éducatif"],
    duration: "court",
    material: false,
    noise: "silencieux",
  },
  {
    name:"Faire un jeu de role", 
    location: ["interieur", "exterieur"],
    min_players: 2,
    max_players: 6,
    energy: "moyen",
    type: ["jeu", "créatif"],
    duration: "long",
    material: false,
    noise: "moyen",
  },
  {
    name:"Jouer a faire semblant", 
    location: ["interieur", "exterieur"],
    min_players: 1,
    max_players: 6,
    energy: "élevé",
    type: ["sport"],
    energy: "moyen",
    type: ["jeu", "créatif"],
    duration: "court",
    material: false,
    noise: "bruyant",
  },
  {
    name:"Creer un film avec un telephone", 
    location: ["interieur", "exterieur"],
    min_players: 1,
    max_players: 6,
    energy: "moyen",
    type: ["créatif", "éducatif"],
    duration: "moyen",
    material: true,
    noise: "moyen",
  },
  {
    name:"Faire une interview en famille", 
    location: ["interieur"],
    min_players: 2,
    max_players: 6,
    energy: "calme",
    type: ["éducatif", "créatif"],
    duration: "court",
    material: true,
    noise: "silencieux",
  },
  {
    name:"Faire des crepes", 
    location: ["interieur"],
    min_players: 1,
    max_players: 6,
    energy: "moyen",
    type: ["créatif"],
    duration: "court",
    material: true,
    noise: "moyen",
  },
  {
    name:"Preparer un repas ensemble", 
    location: ["interieur"],
    min_players: 1,
    max_players: 6,
    energy: "moyen",
    type: ["créatif", "éducatif"],
    duration: "moyen",
    material: true,
    noise: "moyen",
  },
  {
    name:"Decorer des cupcakes", 
    location: ["interieur"],
    min_players: 1,
    max_players: 6,
    energy: "calme",
    type: ["créatif"],
    duration: "court",
    material: true,
    noise: "silencieux",
  },
  {
    name:"Faire une pizza maison", 
    location: ["interieur"],
    min_players: 1,
    max_players: 6,
    energy: "moyen",
    type: ["créatif"],
    duration: "moyen",
    material: true,
    noise: "moyen",
  },
  {
    name:"Tester une nouvelle recette", 
    location: ["interieur"],
    min_players: 1,
    max_players: 6,
    energy: "moyen",
    type: ["créatif", "éducatif"],
    duration: "moyen",
    material: true,
    noise: "moyen",
  },
  {
    name:"Faire un smoothie", 
    location: ["interieur"],
    min_players: 1,
    max_players: 4,
    energy: "calme",
    type: ["créatif"],
    duration: "court",
    material: true,
    noise: "moyen",
  },
  {
    name:"Preparer un gouter", 
    location: ["interieur"],
    min_players: 1,
    max_players: 6,
    energy: "calme",
    type: ["créatif"],
    duration: "court",
    material: true,
    noise: "moyen",
  },
  {
    name:"Resoudre des enigmes", 
    location: ["interieur"],
    min_players: 1,
    max_players: 6,
    energy: "calme",
    type: ["éducatif", "jeu"],
    duration: "court",
    material: true,
    noise: "silencieux",
  },
  {
    name:"Faire un escape game maison", 
    location: ["interieur"],
    min_players: 2,
    max_players: 6,
    energy: "moyen",
    type: ["éducatif", "jeu"],
    duration: "moyen",
    material: true,
    noise: "moyen",
  },
  {
    name:"Apprendre un tour de magie", 
    location: ["interieur"],
    min_players: 1,
    max_players: 4,
    energy: "calme",
    type: ["éducatif", "créatif"],
    duration: "court",
    material: true,
    noise: "silencieux",
  },
  {
    name:"Apprendre quelques mots d'une langue", 
    location: ["interieur"],
    min_players: 1,
    max_players: 6,
    energy: "calme",
    type: ["éducatif"],
    duration: "court",
    material: false,
    noise: "silencieux",
  },
  {
    name:"Regarder une video educative", 
    location: ["interieur"],
    min_players: 1,
    max_players: 6,
    energy: "calme",
    type: ["éducatif", "détente"],
    duration: "court",
    material: true,
    noise: "silencieux",
  },
  {
    name:"Faire des exercices ludiques", 
    location: ["interieur"],
    min_players: 1,
    max_players: 4,
    energy: "moyen",
    type: ["éducatif"],
    duration: "court",
    material: true,
    noise: "silencieux",
  },
  {
    name:"Jouer a des jeux de logique", 
    location: ["interieur"],
    min_players: 1,
    max_players: 4,
    energy: "calme",
    type: ["éducatif", "jeu"],
    duration: "court",
    material: true,
    noise: "silencieux",
  },
  {
    name:"Apprendre une nouvelle competence", 
    location: ["interieur", "exterieur"],
    min_players: 1,
    max_players: 4,
    energy: "moyen",
    type: ["éducatif"],
    duration: "moyen",
    material: false,
    noise: "silencieux",
  },
  {
    name:"Creer une video", 
    location: ["interieur", "exterieur"],
    min_players: 1,
    max_players: 6,
    energy: "moyen",
    type: ["créatif"],
    duration: "moyen",
    material: true,
    noise: "moyen",
  },
  {
    name:"Faire du dessin numérique", 
    location: ["interieur"],
    min_players: 1,
    max_players: 4,
    energy: "calme",
    type: ["créatif"],
    duration: "court",
    material: true,
    noise: "silencieux",
  },
  {
    name:"Utiliser une application educative", 
    location: ["interieur"],
    min_players: 1,
    max_players: 2,
    energy: "calme",
    type: ["éducatif"],
    duration: "court",
    material: true,
    noise: "silencieux",
  },
  {
    name:"Faire un debat amusant", 
    location: ["interieur"],
    min_players: 2,
    max_players: 8,
    energy: "moyen",
    type: ["éducatif", "jeu"],
    duration: "court",
    material: false,
    noise: "moyen",
  },
  {
    name:"Jouer a tu preferes", 
    location: ["interieur", "exterieur"],
    min_players: 2,
    max_players: 8,
    energy: "calme",
    type: ["jeu"],
    duration: "court",
    material: false,
    noise: "silencieux",
  },
  {
    name:"Faire un jeu de questions", 
    location: ["interieur", "exterieur"],
    min_players: 2,
    max_players: 8,
    energy: "calme",
    type: ["jeu", "éducatif"],
    duration: "court",
    material: false,
    noise: "silencieux",
  },
  {
    name:"Ranger ensemble en musique", 
    location: ["interieur"],
    min_players: 1,
    max_players: 6,
    energy: "moyen",
    type: ["détente"],
    duration: "court",
    material: true,
    noise: "moyen",
  },
  {
    name:"Organiser une journee speciale", 
    location: ["interieur", "exterieur"],
    min_players: 2,
    max_players: 8,
    energy: "moyen",
    type: ["créatif", "détente"],
    duration: "long",
    material: false,
    noise: "moyen",
  },
  {
    name:"Creer une tradition familiale", 
    location: ["interieur", "exterieur"],
    min_players: 2,
    max_players: 8,
    energy: "calme",
    type: ["détente", "créatif"],
    duration: "moyen",
    material: false,
    noise: "silencieux",
  },
  {
    name:"Regarder des photos souvenirs", 
    location: ["interieur"],
    min_players: 1,
    max_players: 8,
    energy: "calme",
    type: ["détente"],
    duration: "court",
    material: true,
    noise: "silencieux",
  },
  {
    name:"Ecrire une lettre", 
    location: ["interieur"],
    min_players: 1,
    max_players: 4,
    energy: "calme",
    type: ["créatif", "éducatif"],
    duration: "court",
    material: true,
    noise: "silencieux",
  },


];

export default seedActivities;